apiVersion: v1
kind: Secret
metadata:
  name: redpanda-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{ htpasswd .Values.redpanda.credentials.username .Values.redpanda.credentials.password | b64enc }}