argocd:
  appname: ${NAMESPACE}
  namespace: argocd

project: default
  
cluster:
  address: https://kubernetes.default.svc
  namespace: ${NAMESPACE}
  issuer: ${CERT_ISSUER}
  kubeStateHost: ${KUBEMETRICSSVC}

namespaceTag: ${NAMESPACETAG}
domainSuffix: ${DOMAINSUFFIX}

hashicorp:
  service: "http://vault-common.common.svc.cluster.local:8200"
  secretEngine: ${SECRETENGINE}
  role: ${SECRETROLE}

values:
  repo_URL: https://code.europa.eu/simpl/simpl-open/development/agents/common_components.git
  branch: develop

monitoring:
  enabled: true
  operator:
    repo_URL: https://helm.elastic.co/
    chart_name: eck-operator
    crds_chart_name: eck-operator-crds
    targetRevision: "2.16.1"
    nameOverride: eck-operator
    managedNamespaces: "common,authority1,dataprovider01,consumer01,authority2,dataprovider02,consumer02,authority3,dataprovider03,consumer03"
    valueFiles:
      - values.yaml
  projectID: "828"
  targetRevision: 0.1.11
  chart_name: eck-monitoring
  fullnameOverride: elastic
  params:
    diskSpace: 
      elasticsearch: 50Gi
      logstash: 3Gi
    count:
      elasticsearch: 3
      kibana: 1
      logstash: 1

vault:
  repo_URL: 'https://helm.releases.hashicorp.com'
  targetRevision: 0.29.1
  chart_name: vault
  resources:
    requests:
      cpu: "0"
      memory: "0"

confluent_operator:
  repo_URL: https://packages.confluent.io/helm
  chart_name: confluent-for-kubernetes
  targetRevision: 0.1193.1
  nameOverride: confluent-operator

kafka:
  projectID: "976"
  targetRevision: 1.0.1
  chart_name: kafka
  auth: 
    enabled: true
  topic:
    autocreate: false
  valueFiles:
    - values.yaml

redpanda:
  repo_URL: https://charts.redpanda.com
  chart_name: console
  targetRevision: 0.7.31
  nameOverride: redpanda
  valueFiles:
    - values.yaml
