ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/renew-before: "720h"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
